name: Terraform Outputs
description: Download and export Terraform output from a previous workflow

inputs:
    github_token:
        description: 'GitHub token to access the workflow artifacts'
        required: true

    workflow:
        description: 'The workflow file name to download the artifacts from'
        required: true

    branch:
        description: 'The branch to download the artifacts from'
        required: true

outputs:
    ecr_repository_name:
        description: 'The ECR repository name output from Terraform'
        value: ${{ steps.outputs.outputs.ecr_repository_name }}
    container_name:
        description: 'The container name output from Terraform'
        value: ${{ steps.outputs.outputs.container_name }}
    ecs_cluster_name:
        description: 'The ECS cluster name output from Terraform'
        value: ${{ steps.outputs.outputs.ecs_cluster_name }}
    ecs_service_name:
        description: 'The ECS service name output from Terraform'
        value: ${{ steps.outputs.outputs.ecs_service_name }}
    ecs_task_definition_family:
        description: 'The ECS task definition family output from Terraform'
        value: ${{ steps.outputs.outputs.ecs_task_definition_family }}

runs:
    using: composite
    steps:
        - name: Download Artifacts from Terraform Apply Workflow
          uses: dawidd6/action-download-artifact@v21
          with:
              github_token: ${{ inputs.github_token }}
              workflow: ${{ inputs.workflow }}
              branch: ${{ inputs.branch }}
              workflow_conclusion: success
              name: terraform-production-output
              path: terraform-output
              search_artifacts: true
        - name: Validate Output File
          shell: bash
          run: |
              if [ ! -f terraform-output/terraform-output.json ]; then
                  echo "Terraform output file not found!"
                  exit 1
              fi

        - name: Export Terraform Outputs
          id: outputs
          shell: bash
          run: |
              OUTPUT_FILE="terraform-output/terraform-output.json"
              if [ ! -f "$OUTPUT_FILE" ]; then
                  echo "Terraform output file not found!"
                  exit 1
              fi

              ECR_REPOSITORY_NAME=$(jq -r '.ecr_repository_name.value' "$OUTPUT_FILE")
              ECS_CLUSTER_NAME=$(jq -r '.ecs_cluster_name.value' "$OUTPUT_FILE")
              ECS_SERVICE_NAME=$(jq -r '.ecs_service_name.value' "$OUTPUT_FILE")
              ECS_TASK_DEFINITION_FAMILY=$(jq -r '.ecs_task_definition_family.value' "$OUTPUT_FILE")
              CONTAINER_NAME=$(jq -r '.container_name.value' "$OUTPUT_FILE")

              echo "ecr_repository_name=$ECR_REPOSITORY_NAME" >> $GITHUB_OUTPUT
              echo "ecs_cluster_name=$ECS_CLUSTER_NAME" >> $GITHUB_OUTPUT
              echo "ecs_service_name=$ECS_SERVICE_NAME" >> $GITHUB_OUTPUT
              echo "ecs_task_definition_family=$ECS_TASK_DEFINITION_FAMILY" >> $GITHUB_OUTPUT
              echo "container_name=$CONTAINER_NAME" >> $GITHUB_OUTPUT
