name: Continuous Integration

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    backend:
        name: Backend Quality Checks
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
                shell: bash

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Install Node.js and Setup PNPM
              uses: pnpm/setup@v1
              with:
                  runtime: node@lts
                  version: 11.9.0
                  install: false
                  cache: true
                  cache-dependency-path: backend/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run ESLint
              run: pnpm lint

            - name: Run Unit Tests
              run: pnpm test

            - name: Build Application
              run: pnpm build

    terraform:
        name: Terraform Validate
        runs-on: ubuntu-latest
        strategy:
            matrix:
                environment:
                    - production
                    - staging
        environment: ${{ matrix.environment }}
        defaults:
            run:
                working-directory: infra/environments/${{ matrix.environment }}
                shell: bash

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.3
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: 1.15.0

            - name: Setup TFLint
              uses: terraform-linters/setup-tflint@v6
              with:
                  tflint_version: latest

            - name: Terraform Lint
              run: |
                  cd ../../
                  tflint --init
                  tflint --recursive -f compact

            - name: Validate Terraform configuration and formatting
              run: |
                  terraform init -backend=false
                  terraform fmt -check -recursive
                  terraform validate
            - name: Terraform Plan
              run: |
                  terraform init
                  terraform plan \
                  -out=${{ matrix.environment }}.tfplan \
                  -var="environment=${{ matrix.environment }}" \
                  -var="aws_region=${{ vars.TF_VAR_AWS_REGION }}" \
                  -var="project_name=${{ vars.TF_VAR_PROJECT_NAME }}" \
                  -var="vpc_cidr=${{ vars.TF_VAR_VPC_CIDR }}" \
                  -var="availability_zone_count=${{ vars.TF_VAR_AVAILABILITY_ZONE_COUNT }}"\
                  -var="ssl_policy=${{ secrets.TF_VAR_SSL_POLICY }}" \
                  -var="root_domain_name=${{ vars.TF_VAR_ROOT_DOMAIN_NAME }}" \
                  -var="sub_domain=${{ vars.TF_VAR_SUB_DOMAIN }}"
