name: Continuous Integration

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    backend:
        name: Backend Quality Checks
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
                shell: bash

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Install Node.js and Setup PNPM
              uses: pnpm/setup@v1
              with:
                  runtime: node@lts
                  version: 11.9.0
                  install: false
                  cache: true
                  cache-dependency-path: backend/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run ESLint
              run: pnpm lint

            - name: Run Unit Tests
              run: pnpm test

            - name: Build Application
              run: pnpm build

    terraform:
        name: Terraform Validate
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: infra
                shell: bash

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.3
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: 1.15.0

            - name: Setup TFLint
              uses: terraform-linters/setup-tflint@v6
              with:
                  tflint_version: latest

            - name: Validate Terraform format and linting
              run: |
                  terraform fmt -check -recursive
                  tflint --init
                  tflint --recursive -f compact

            - name: Validate Terraform configuration
              run: |
                  terraform init -backend=false
                  terraform validate
            - name: Terraform Plan
              run: |
                  terraform init
                  terraform plan \
                  -out=production.tfplan \
                  -var="region=${{ vars.AWS_REGION }}" \
                  -var="environment=production" \
                  -var="project_name=${{ vars.PROJECT_NAME }}" \
                  -var="vpc_cidr=${{ vars.VPC_CIDR }}" \
                  -var="availability_zone_count=${{ vars.AVAILABILITY_ZONE_COUNT }}"
