name: 'Deploy Backend Application'
run-name: 'Deploy Backend Application - ${{ github.ref_name }}'

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
            - '.github/workflows/deploy.yaml'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
    group: deploy-production
    cancel-in-progress: true

jobs:
    build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                working-directory: backend
                shell: bash

        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Login to Amazon ECR
              id: ecr-login
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and Push Docker Image to ECR
              id: docker
              uses: ./.github/workflows/actions/docker-build
              with:
                  registry: ${{ steps.ecr-login.outputs.registry }}
                  repository: ${{ vars.AWS_ECR_REPOSITORY_NAME }}
                  image_tag: ${{ github.sha }}
                  context: backend
                  build_args: 'NODE_ENV=production'

            - name: Deploy to Amazon ECS
              uses: ./.github/workflows/actions/ecs-deploy
              with:
                  task-definition-family: ${{ vars.AWS_ECS_TASK_DEFINITION_FAMILY }}
                  cluster: ${{ vars.AWS_ECS_CLUSTER_NAME }}
                  service: ${{ vars.AWS_ECS_SERVICE_NAME }}
                  container-name: ${{ vars.AWS_ECS_CONTAINER_NAME }}
                  image-uri: ${{ steps.docker.outputs.image_uri }}
                  rollback-on-failure: true
