name: 'Deploy Backend Application'
run-name: 'Deploy Backend Application - ${{ github.ref_name }}'

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
            - '.github/workflows/deploy.yml'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
    group: deploy-production
    cancel-in-progress: true

jobs:
    build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                working-directory: backend
                shell: bash

        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Login to Amazon ECR
              id: ecr-login
              uses: aws-actions/amazon-ecr-login@v2

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Download Artifacts from Terraform Apply Workflow
              uses: dawidd6/action-download-artifact@v21
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  workflow: .github/workflows/terraform-apply.yml
                  branch: main
                  workflow_conclusion: success
                  name: terraform-production-output
                  path: backend/output
                  search_artifacts: true

            - name: Read and Export Terraform Output Variables
              run: |
                  JSON_PATH="./output/output.json"
                  echo "ECR_REPOSITORY_NAME=$(jq -r '.ecr_repository_name.value' $JSON_PATH)" >> $GITHUB_ENV
                  echo "ECS_CLUSTER_NAME=$(jq -r '.ecs_cluster_name.value' $JSON_PATH)" >> $GITHUB_ENV
                  echo "ECS_SERVICE_NAME=$(jq -r '.ecs_service_name.value' $JSON_PATH)" >> $GITHUB_ENV
                  echo "ECS_TASK_DEFINITION_FAMILY=$(jq -r '.ecs_task_definition_family.value' $JSON_PATH)" >> $GITHUB_ENV

            - name: Generate Short Image Tag
              run: |
                  IMAGE_TAG=${GITHUB_SHA::7}
                  echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

            - name: Build Docker Image
              run: |
                  docker build \
                    -t ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY_NAME:$IMAGE_TAG \
                    --build-arg NODE_ENV=production \
                    .

            - name: Push Docker Image to ECR
              run: |
                  docker push ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY_NAME:$IMAGE_TAG

            - name: Download Current Task Definition
              run: |
                  aws ecs describe-task-definition \
                    --task-definition $ECS_TASK_DEFINITION_FAMILY \
                    --query 'taskDefinition' \
                    --output json > current_task_definition.json

            - name: Update Task Definition
              run: |
                  IMAGE="${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY_NAME:$IMAGE_TAG"
                  jq --arg IMAGE "$IMAGE" \
                    '
                    del(
                      .taskDefinitionArn,
                      .revision,
                      .status,
                      .requiresAttributes,
                      .compatibilities,
                      .registeredAt,
                      .registeredBy
                    )
                    | .containerDefinitions[0].image = $IMAGE
                    ' \
                    current_task_definition.json > updated_task_definition.json
            - name: Register New Task Definition
              id: register-task
              run: |
                TASK_DEFINITION_ARN=$(
                  aws ecs register-task-definition \
                    --cli-input-json file://updated_task_definition.json \
                    --query 'taskDefinition.taskDefinitionArn' \
                    --output text
                )
            
                echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> "$GITHUB_ENV"
                echo "task_definition_arn=$TASK_DEFINITION_ARN" >> "$GITHUB_OUTPUT"
            - name: Show Registered Task Definition adn the updated_task_definition.json
              run: |
                echo "$TASK_DEFINITION_ARN"
                cat updated_task_definition.json
            - name: Deploy to ECS
              run: |
                aws ecs update-service \
                  --cluster "$ECS_CLUSTER_NAME" \
                  --service "$ECS_SERVICE_NAME" \
                  --task-definition "$TASK_DEFINITION_ARN"
                  
