name: 'Terraform Plan'
run-name: 'Terraform Plan for ${{ github.ref_name }}'

on:
    pull_request:
        branches:
            - main
        paths:
            - './**'
            - 'infra/environments/staging/**'
            - 'infra/modules/**'
            - '.github/workflows/terraform-plan.yaml'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pull-requests: write

concurrency:
    group: 'terraform-plan-${{ github.ref_name }}'
    cancel-in-progress: true

jobs:
    change-detection:
        runs-on: ubuntu-latest
        name: Detect Changes in Terraform Files
        outputs:
            staging: ${{ steps.filter.outputs.staging }}
            production: ${{ steps.filter.outputs.production }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7
            - name: Detect Changes
              uses: dorny/paths-filter@v4
              id: filter
              with:
                  filters: |
                      staging:
                          - 'infra/environments/staging/**'
                          - 'infra/modules/**'
                      production:
                          - 'infra/environments/production/**'
                          - 'infra/modules/**'

    plan-staging:
        name: Plan Staging
        runs-on: ubuntu-latest
        needs: change-detection
        defaults:
            run:
                working-directory: infra/environments/staging
                shell: bash
        environment: staging
        if: ${{ github.event_name == 'workflow_dispatch' || needs.change-detection.outputs.staging == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Terraform Setup and Validate
              uses: ./.github/workflows/actions/terraform-setup-and-validate
              with:
                  working_directory: infra/environments/staging

            - name: Terraform Staging Plan and Archive
              id: archive
              uses: ./.github/workflows/actions/terraform-plan-archive
              with:
                  environment: staging
                  archive_name: terraform-plan-staging
                  working_directory: infra/environments/staging
                  archive_retention_days: 7

            - name: Artifact URL
              run: |
                  echo "Terraform plan files archived at: ${{ steps.archive.outputs.archive_url }}"

    plan-production:
        name: Plan Production
        runs-on: ubuntu-latest
        needs: change-detection
        defaults:
            run:
                working-directory: infra/environments/production
                shell: bash
        environment: production
        if: ${{ github.event_name == 'workflow_dispatch' || needs.change-detection.outputs.production == 'true' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Terraform Setup and Validate
              uses: ./.github/workflows/actions/terraform-setup-and-validate
              with:
                  working_directory: infra/environments/production

            - name: Terraform Production Plan and Archive
              id: archive
              uses: ./.github/workflows/actions/terraform-plan-archive
              with:
                  environment: production
                  archive_name: terraform-plan-production
                  working_directory: infra/environments/production
                  archive_retention_days: 7

            - name: Artifact URL
              run: |
                  echo "Terraform plan files archived at: ${{ steps.archive.outputs.archive_url }}"
