name: 'Terraform Apply'

on:
    push:
        branches:
            - main
        paths:
            - 'infra/environments/production/**'
            - 'infra/modules/**'
            - '.github/workflows/terraform-apply.yaml'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

concurrency:
    group: terraform-apply-production
    cancel-in-progress: false

jobs:
    terraform-apply:
        name: Apply Terraform Changes
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: infra/environments/production
                shell: bash
        environment: production
        steps:
            - uses: actions/checkout@v7
            - uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Terraform Setup and Validate
              uses: ./.github/workflows/actions/terraform-setup-and-validate
              with:
                  working_directory: infra/environments/production
                  terraform_version: '1.15.0'
                  tflint_version: 'latest'

            - name: Terraform init
              run: |
                  terraform init

            - name: Terraform plan
              run: |
                  terraform plan -input=false -out=tfplan

            - name: Terraform apply
              run: |
                  terraform apply -input=false tfplan

            - name: Terraform show
              run: |
                  terraform show -no-color tfplan > plan.txt

            - name: Terraform output
              run: |
                  terraform output -json > output.json

            - name: Upload Terraform Output
              uses: actions/upload-artifact@v7
              with:
                  name: terraform-production-output
                  path: |
                      infra/environments/production/output.json
                      infra/environments/production/plan.txt
                  retention-days: 7
